# Generated by Django 3.1.7 on 2021-03-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_date', models.DateTimeField(auto_now_add=True, verbose_name='changed date')),
                ('old_path', models.CharField(max_length=300, verbose_name='old name')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_history', to='app.picture')),
            ],
        ),
    ]
